name: Sync Packagist
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Debug Packagist API
        run: |
          curl -X POST "https://packagist.org/api/update-package?username=gergo-tar&apiToken=${{ secrets.PACKAGIST_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"repository":"https://github.com/gergo-tar/laravel-package-skeleton"}'
